language: php
php:
  - 7.1
  - 7.2
services:
  - rabbitmq
  - memcached
  - mongodb
  - mysql
sudo: required
dist: xenial
env:
  - V8=6.6 PHP_V8=0.2.2
before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add tests/config.ini
  - sudo add-apt-repository -y ppa:pinepain/libv8
  - sudo apt-get update -y
  - sudo apt-get install -y libv8-${V8}-dev
  - git clone https://github.com/pinepain/php-v8.git
  - cd php-v8
  - git checkout tags/v${PHP_V8}
  - phpize && ./configure && make
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then cp modules/v8.so /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20160303/v8.so; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then cp modules/v8.so /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20170718/v8.so; fi;
  - cd ..
  - echo "extension=v8.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo apt-get install beanstalkd
  - pushd /tmp && wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.1.zip && unzip elasticsearch-5.2.1.zip && popd
install:
  - composer install
before_script:
  - beanstalkd -l 127.0.0.1 -p 11300 &
  - mysql -e 'create database app_news;'
  - /tmp/elasticsearch-5.2.1/bin/elasticsearch &
  - sleep 12
script:
  - vendor/bin/phpunit --verbose
