language: php
php:
  - 7.0
  - 7.1
services:
  - rabbitmq
  - elasticsearch
  - memcached
  - mongodb
  - redis
  - mysql
sudo: required
dist: trusty
env:
  - V8=5.8 PHP_V8=0.1.2
before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add tests/config.ini
  - sudo add-apt-repository -y ppa:pinepain/libv8-${V8}
  - sudo apt-get update -y
  - sudo apt-get install -y libv8-${V8}-dev
  - git clone https://github.com/pinepain/php-v8.git
  - cd php-v8
  - git checkout tags/v${PHP_V8}
  - phpize && ./configure && make
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then cp modules/v8.so /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20151012/v8.so; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then cp modules/v8.so /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20160303/v8.so; fi;
  - cd ..
  - echo "extension=v8.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo apt-get install beanstalkd
install:
  - composer install
before_script:
  - beanstalkd -l 127.0.0.1 -p 11300 &
  - mysql -e 'create database app;'
script:
  - vendor/bin/phpunit
